# Generated by Django 3.2.15 on 2022-09-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, upload_to="raizalduo"),
        ),
    ]
