# Generated by Django 3.2.15 on 2022-09-23 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20220923_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shows',
            old_name='show',
            new_name='title',
        ),
    ]
