# Generated by Django 3.2.15 on 2022-09-25 03:51

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_rename_show_shows_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", embed_video.fields.EmbedVideoField()),
            ],
        ),
    ]
