# Generated by Django 4.1.1 on 2022-09-30 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_lucia_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lucia',
        ),
    ]
