# Generated by Django 4.1.1 on 2022-10-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0013_remove_post_image_alter_post_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Draft"), (1, "Published")], default=1
            ),
        ),
    ]
