# Generated by Django 4.1.1 on 2022-10-02 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_rename_image_post_featured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='url',
            new_name='video',
        ),
    ]
