# Generated by Django 4.1.1 on 2022-10-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0017_rename_url_video_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Draft"), (1, "Published")], default=1
            ),
        ),
    ]
