# Generated by Django 4.1.1 on 2022-10-02 23:17

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0019_alter_video_options_comment_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="video",
        ),
        migrations.AddField(
            model_name="post",
            name="video",
            field=embed_video.fields.EmbedVideoField(default=False),
        ),
    ]
