# Generated by Django 4.1.1 on 2022-10-02 23:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0020_remove_comment_video_post_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="video",
        ),
    ]
