# Generated by Django 4.1.2 on 2022-10-05 01:19

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_remove_video_video_videomusic_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='url',
            field=embed_video.fields.EmbedVideoField(default=1),
        ),
    ]
