# Generated by Django 4.1.2 on 2022-10-05 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_comment_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='url',
        ),
    ]
