# Generated by Django 4.1.2 on 2022-10-22 05:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0030_alter_comment_approved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
        migrations.RemoveField(
            model_name="post",
            name="content",
        ),
        migrations.RemoveField(
            model_name="post",
            name="excerpt",
        ),
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
        migrations.RemoveField(
            model_name="post",
            name="updated_on",
        ),
    ]
